title: Klinik Research Korporation
description: A production, development and research blog focusing on experimental electronic music
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

#baseurl: "/site"
url: "https://klinikaudio.github.io" # Also good practice to set the production URL